# -*- coding: utf-8 -*-
"""Image download from google.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14EXQ7oJFKYqYVqKKcUCrjLqgY7llbRzK
"""

! pip install simple_image_download

from simple_image_download import simple_image_download as simp 
response = simp.simple_image_download

lst=['Sachin Tendulkar', 'Amitabh Bachchan', 'Sania Mirza','Shah Rukh Khan','Kajol']

for rep in lst:
    response().download(rep +' face' , 30)

!zip -r simple_images.zip simple_images